edges:
  - tstore:
      serviceDef:
        proto: "http"
        host: "localhost"
        port: 8443
      servicePath:
        path: "/v1"
        method: "post"
        concurrency: 16
        timeout: 4
        errorPercent: 25
  - payments:
      serviceDef:
        proto: "http"
        host: "localhost"
        port: 8443
      servicePath:
        path: "/v1"
        method: "post"
        concurrency: 16
        timeout: 4
        errorPercent: 40
